"""empty message

Revision ID: 073ab07f8793
Revises: 4842806dd802
Create Date: 2023-09-11 19:04:48.959519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '073ab07f8793'
down_revision = '4842806dd802'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=345), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    # ### end Alembic commands ###


def upgrade_prefixed():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_prefixed():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

