"""empty message

Revision ID: 087c8e6177e0
Revises: 1a6bb4fbf6ff
Create Date: 2023-09-24 02:56:57.573689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '087c8e6177e0'
down_revision = '1a6bb4fbf6ff'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Quiz',
    sa.Column('Quiz_ID', sa.String(length=32), nullable=False),
    sa.Column('Quiz_Name', sa.String(length=120), nullable=True),
    sa.Column('Quiz_Time', sa.DateTime(), nullable=True),
    sa.Column('Quiz_UserID', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['Quiz_UserID'], ['Users.username'], ),
    sa.PrimaryKeyConstraint('Quiz_ID'),
    sa.UniqueConstraint('Quiz_ID')
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Quiz')
    # ### end Alembic commands ###


def upgrade_prefixed():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_prefixed():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

