"""empty message

Revision ID: 1a6bb4fbf6ff
Revises: c0551ddb720b
Create Date: 2023-09-24 01:40:09.593429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a6bb4fbf6ff'
down_revision = 'c0551ddb720b'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Quiz',
    sa.Column('Quiz_ID', sa.String(length=32), nullable=False),
    sa.Column('Quiz_Name', sa.String(length=120), nullable=True),
    sa.Column('Quiz_Time', sa.DateTime(), nullable=True),
    sa.Column('Quiz_UserID', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['Quiz_UserID'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('Quiz_ID'),
    sa.UniqueConstraint('Quiz_ID')
    )
    op.create_table('Quiz_QA',
    sa.Column('QA_ID', sa.String(length=32), nullable=False),
    sa.Column('QA_Question', sa.String(length=300), nullable=True),
    sa.Column('QA_Answer', sa.String(length=400), nullable=True),
    sa.Column('QA_QuizID', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['QA_QuizID'], ['Quiz.Quiz_ID'], ),
    sa.PrimaryKeyConstraint('QA_ID'),
    sa.UniqueConstraint('QA_ID')
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Quiz_QA')
    op.drop_table('Quiz')
    # ### end Alembic commands ###


def upgrade_prefixed():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_prefixed():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

