"""empty message

Revision ID: 7a8d901c4610
Revises: 065e2f14de2e
Create Date: 2023-09-20 12:11:28.754375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a8d901c4610'
down_revision = '065e2f14de2e'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=345), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_index('ix_User_token')

    op.drop_table('User')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('username', sa.VARCHAR(length=40), nullable=True),
    sa.Column('email', sa.VARCHAR(length=345), nullable=True),
    sa.Column('password_hash', sa.TEXT(), nullable=False),
    sa.Column('token', sa.VARCHAR(length=32), nullable=True),
    sa.Column('token_expiration', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.create_index('ix_User_token', ['token'], unique=False)

    op.drop_table('Users')
    # ### end Alembic commands ###


def upgrade_prefixed():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_prefixed():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

