"""empty message

Revision ID: d7e9ebf32612
Revises: e9c77cb56f6a
Create Date: 2023-09-24 03:49:41.355588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7e9ebf32612'
down_revision = 'e9c77cb56f6a'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=345), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Quiz',
    sa.Column('ID', sa.String(length=32), nullable=False),
    sa.Column('Name', sa.String(length=120), nullable=True),
    sa.Column('Start_Time', sa.DateTime(), nullable=True),
    sa.Column('UserID', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Quiz')
    op.drop_table('Users')
    # ### end Alembic commands ###


def upgrade_prefixed():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_prefixed():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

