"""empty message

Revision ID: f95cf120ee4a
Revises: d7e9ebf32612
Create Date: 2023-09-24 03:57:37.176633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f95cf120ee4a'
down_revision = 'd7e9ebf32612'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('userid', sa.String(length=40), nullable=True))
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'Users', ['userid'], ['id'])
        batch_op.drop_column('ID')
        batch_op.drop_column('Name')
        batch_op.drop_column('Start_Time')
        batch_op.drop_column('UserID')

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('UserID', sa.VARCHAR(length=40), nullable=True))
        batch_op.add_column(sa.Column('Start_Time', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('Name', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('ID', sa.VARCHAR(length=32), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'Users', ['UserID'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('userid')
        batch_op.drop_column('start_time')
        batch_op.drop_column('name')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def upgrade_prefixed():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_prefixed():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

