"""empty message

Revision ID: ffffee3b3d48
Revises: 087c8e6177e0
Create Date: 2023-09-24 03:47:34.757969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffffee3b3d48'
down_revision = '087c8e6177e0'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ID', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('Name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('Start_Time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('UserID', sa.String(length=40), nullable=True))
        batch_op.create_unique_constraint(None, ['ID'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'Users', ['UserID'], ['id'])
        batch_op.drop_column('Quiz_Time')
        batch_op.drop_column('Quiz_UserID')
        batch_op.drop_column('Quiz_ID')
        batch_op.drop_column('Quiz_Name')

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Quiz_Name', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('Quiz_ID', sa.VARCHAR(length=32), nullable=False))
        batch_op.add_column(sa.Column('Quiz_UserID', sa.VARCHAR(length=40), nullable=True))
        batch_op.add_column(sa.Column('Quiz_Time', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'Users', ['Quiz_UserID'], ['username'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('UserID')
        batch_op.drop_column('Start_Time')
        batch_op.drop_column('Name')
        batch_op.drop_column('ID')

    # ### end Alembic commands ###


def upgrade_prefixed():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_prefixed():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

