"""empty message

Revision ID: 0f83f38b8cc8
Revises: 9ca17cd53e7a
Create Date: 2023-09-06 19:15:53.205200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f83f38b8cc8'
down_revision = '9ca17cd53e7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Employee',
    sa.Column('employee_ID', sa.Integer(), nullable=False),
    sa.Column('employee_FirstName', sa.String(length=50), nullable=True),
    sa.Column('employee_LastName', sa.String(length=50), nullable=True),
    sa.Column('employee_Age', sa.Integer(), nullable=True),
    sa.Column('employee_Dept', sa.String(length=50), nullable=True),
    sa.Column('employee_Salary', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('employee_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Employee')
    # ### end Alembic commands ###
