"""empty message

Revision ID: 22ae03a76e96
Revises: 0f83f38b8cc8
Create Date: 2023-09-07 12:24:49.698298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22ae03a76e96'
down_revision = '0f83f38b8cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Employee',
    sa.Column('employee_ID', sa.Integer(), nullable=False),
    sa.Column('employee_FirstName', sa.String(length=50), nullable=True),
    sa.Column('employee_LastName', sa.String(length=50), nullable=True),
    sa.Column('employee_Age', sa.Integer(), nullable=True),
    sa.Column('employee_Dept', sa.String(length=50), nullable=True),
    sa.Column('employee_Salary', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('employee_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Employee')
    # ### end Alembic commands ###
