"""empty message

Revision ID: 26f96f14c156
Revises: 38ed6c156f89
Create Date: 2023-09-07 14:23:52.100220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f96f14c156'
down_revision = '38ed6c156f89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Inventory',
    sa.Column('inventory_ID', sa.Integer(), nullable=False),
    sa.Column('inventory_Quantity', sa.Integer(), nullable=True),
    sa.Column('products_ProductID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['products_ProductID'], ['Products.products_ID'], ),
    sa.PrimaryKeyConstraint('inventory_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Inventory')
    # ### end Alembic commands ###
