"""empty message

Revision ID: 38ed6c156f89
Revises: b2bfe9720d84
Create Date: 2023-09-07 13:45:32.443185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ed6c156f89'
down_revision = 'b2bfe9720d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Employee',
    sa.Column('employee_ID', sa.Integer(), nullable=False),
    sa.Column('employee_FirstName', sa.String(length=50), nullable=True),
    sa.Column('employee_LastName', sa.String(length=50), nullable=True),
    sa.Column('employee_Age', sa.Integer(), nullable=True),
    sa.Column('employee_Dept', sa.String(length=50), nullable=True),
    sa.Column('employee_Salary', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('employee_ID')
    )
    op.create_table('Products',
    sa.Column('products_ID', sa.Integer(), nullable=False),
    sa.Column('products_Name', sa.String(length=50), nullable=True),
    sa.Column('products_Category', sa.String(length=50), nullable=True),
    sa.Column('products_Price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('products_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Products')
    op.drop_table('Employee')
    # ### end Alembic commands ###
