"""empty message

Revision ID: 4113c82f0ac1
Revises: 26f96f14c156
Create Date: 2023-09-08 15:05:03.776631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4113c82f0ac1'
down_revision = '26f96f14c156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Courses',
    sa.Column('courses_ID', sa.String(length=10), nullable=False),
    sa.Column('courses_Name', sa.String(length=100), nullable=True),
    sa.Column('courses_Credit', sa.Integer(), nullable=True),
    sa.Column('courses_Dept', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('courses_ID')
    )
    op.create_table('Course Enrollment',
    sa.Column('enrollment_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enrollment_StudentID', sa.Integer(), nullable=True),
    sa.Column('enrollment_CourseID', sa.String(length=10), nullable=True),
    sa.Column('enrollment_Grade', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_CourseID'], ['Courses.courses_ID'], ),
    sa.PrimaryKeyConstraint('enrollment_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Course Enrollment')
    op.drop_table('Courses')
    # ### end Alembic commands ###
