"""empty message

Revision ID: 8b0e93640398
Revises: fb7d15ccac2e
Create Date: 2023-09-10 03:43:52.742020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b0e93640398'
down_revision = 'fb7d15ccac2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Genre',
    sa.Column('genre_ID', sa.Integer(), nullable=False),
    sa.Column('genre_Name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('genre_ID')
    )
    op.create_table('Artist',
    sa.Column('artist_ID', sa.Integer(), nullable=False),
    sa.Column('artist_Name', sa.String(length=100), nullable=True),
    sa.Column('artist_Country', sa.String(length=60), nullable=True),
    sa.Column('artist_GenreID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_GenreID'], ['Genre.genre_ID'], ),
    sa.PrimaryKeyConstraint('artist_ID')
    )
    op.create_table('Album',
    sa.Column('album_ID', sa.Integer(), nullable=False),
    sa.Column('album_Name', sa.String(length=150), nullable=True),
    sa.Column('album_ReleaseYear', sa.Integer(), nullable=True),
    sa.Column('album_ArtistID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['album_ArtistID'], ['Artist.artist_ID'], ),
    sa.PrimaryKeyConstraint('album_ID')
    )
    op.create_table('Song',
    sa.Column('song_ID', sa.Integer(), nullable=False),
    sa.Column('song_Title', sa.String(length=150), nullable=True),
    sa.Column('song_AlbumID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['song_AlbumID'], ['Album.album_ID'], ),
    sa.PrimaryKeyConstraint('song_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Song')
    op.drop_table('Album')
    op.drop_table('Artist')
    op.drop_table('Genre')
    # ### end Alembic commands ###
