"""empty message

Revision ID: 8b1dc1de20c8
Revises: 
Create Date: 2023-09-09 19:52:11.816987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b1dc1de20c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Course',
    sa.Column('course_ID', sa.String(length=10), nullable=False),
    sa.Column('course_Name', sa.String(length=100), nullable=True),
    sa.Column('course_Credit', sa.Integer(), nullable=True),
    sa.Column('course_Dept', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('course_ID')
    )
    op.create_table('Employee',
    sa.Column('employee_ID', sa.Integer(), nullable=False),
    sa.Column('employee_FirstName', sa.String(length=50), nullable=True),
    sa.Column('employee_LastName', sa.String(length=50), nullable=True),
    sa.Column('employee_Age', sa.Integer(), nullable=True),
    sa.Column('employee_Dept', sa.String(length=50), nullable=True),
    sa.Column('employee_Salary', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('employee_ID')
    )
    op.create_table('Flight',
    sa.Column('flight_ID', sa.Integer(), nullable=False),
    sa.Column('flight_AirlineName', sa.String(length=100), nullable=True),
    sa.Column('flight_DepartureCity', sa.String(length=100), nullable=True),
    sa.Column('flight_ArrivalCity', sa.String(length=100), nullable=True),
    sa.Column('flight_DepartureTime', sa.DateTime(), nullable=True),
    sa.Column('flight_ArrivalTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('flight_ID')
    )
    op.create_table('Passenger',
    sa.Column('passenger_ID', sa.Integer(), nullable=False),
    sa.Column('passenger_FirstName', sa.String(length=50), nullable=True),
    sa.Column('passenger_LastName', sa.String(length=50), nullable=True),
    sa.Column('passenger_Gender', sa.String(length=5), nullable=True),
    sa.Column('passenger_Age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('passenger_ID')
    )
    op.create_table('Product',
    sa.Column('products_ID', sa.Integer(), nullable=False),
    sa.Column('products_Name', sa.String(length=50), nullable=True),
    sa.Column('products_Category', sa.String(length=50), nullable=True),
    sa.Column('products_Price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('products_ID')
    )
    op.create_table('Enrollment',
    sa.Column('enrollment_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enrollment_StudentID', sa.Integer(), nullable=True),
    sa.Column('enrollment_CourseID', sa.String(length=10), nullable=True),
    sa.Column('enrollment_Grade', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_CourseID'], ['Course.course_ID'], ),
    sa.PrimaryKeyConstraint('enrollment_ID')
    )
    op.create_table('Inventory',
    sa.Column('inventory_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inventory_Quantity', sa.Integer(), nullable=True),
    sa.Column('products_ProductID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['products_ProductID'], ['Product.products_ID'], ),
    sa.PrimaryKeyConstraint('inventory_ID')
    )
    op.create_table('Ticket',
    sa.Column('ticket_ID', sa.Integer(), nullable=False),
    sa.Column('ticket_FlightID', sa.Integer(), nullable=True),
    sa.Column('ticket_PassengerID', sa.Integer(), nullable=True),
    sa.Column('ticket_SeatNumber', sa.String(length=4), nullable=True),
    sa.Column('ticket_Price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_FlightID'], ['Flight.flight_ID'], ),
    sa.ForeignKeyConstraint(['ticket_PassengerID'], ['Passenger.passenger_ID'], ),
    sa.PrimaryKeyConstraint('ticket_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Ticket')
    op.drop_table('Inventory')
    op.drop_table('Enrollment')
    op.drop_table('Product')
    op.drop_table('Passenger')
    op.drop_table('Flight')
    op.drop_table('Employee')
    op.drop_table('Course')
    # ### end Alembic commands ###
